apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels: 
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - args:
        - gunicorn
        - --bind
        - 0.0.0.0:5000
        - app:app
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_DEBUG
          value: "1"
        - name: FLASK_ENV
          value: development
        image: backend
        name: backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/app
          name: backend-claim0
      restartPolicy: Always
      volumes:
      - name: backend-claim0
        persistentVolumeClaim:
          claimName: backend-claim0
status: {}
